export const quotes = [
  { text: "The hardest choices require the strongest wills.", author: "Thanos" },
  { text: "With great power comes great responsibility.", author: "Uncle Ben" },
  { text: "I can do this all day.", author: "Steve Rogers" },
  { text: "We don’t get to choose our time.", author: "The Ancient One" },
  { text: "I love you 3000.", author: "Tony Stark" },
  { text: "It's not about how much we lost, it's about how much we have left.", author: "Tony Stark" },
  { text: "I’m just a kid from Brooklyn.", author: "Steve Rogers" },
  { text: "The price of freedom is high, it always has been.", author: "Steve Rogers" },
  { text: "Part of the journey is the end.", author: "Tony Stark" },
  { text: "Sometimes you have to run before you can walk.", author: "Tony Stark" },
  { text: "But a thing isn’t beautiful because it lasts.", author: "Vision" },
  { text: "No man can win every battle, but no man should fall without a struggle.", author: "Peter Parker" },
  { text: "What is grief, if not love persevering?", author: "Vision" },
  { text: "You never know. You hope for the best and make do with what you get.", author: "Nick Fury" },
  { text: "It's not who I am underneath, but what I do that defines me.", author: "Bruce Wayne" },
  { text: "The world has changed. None of us can go back.", author: "Steve Rogers" },
  { text: "Whatever it takes.", author: "Various Avengers" },
  { text: "You’re not the guy to make the sacrifice play.", author: "Tony Stark" },
  { text: "Everyone fails at who they’re supposed to be.", author: "Thor" },
  { text: "I know my worth.", author: "Carol Danvers" }
];
